/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4DgXBfevHsz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function aboutComp() {
  return (
    <div className="bg-gray-100 white:bg-gray-800">
      <div className="container mx-auto py-12 md:py-16 lg:py-20">
        <div className="grid grid-cols-1 gap-8 md:gap-12">
          <div className="bg-white white:bg-gray-900 rounded-lg overflow-hidden">
            <div className="grid md:grid-cols-2">
              <div>
                <img
                  alt="About Page Cover"
                  className="w-full h-[300px] md:h-full object-cover"
                  height={600}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/600",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
              <div className="p-6 md:p-8">
                <h1 className="text-3xl md:text-4xl font-bold mb-2">About Our Blogging Website</h1>
                <div className="flex items-center text-gray-500 white:text-gray-400 mb-4">
                  <span>Established in 2023</span>
                </div>
                <p className="text-gray-600 white:text-gray-300 leading-relaxed mb-4">
                  Welcome to our blogging website, where we're passionate about sharing our insights, experiences, and
                  perspectives with the world. Our mission is to inspire, educate, and engage our readers through
                  thought-provoking and informative content.
                </p>
                <p className="text-gray-600 white:text-gray-300 leading-relaxed mb-4">
                  At the heart of our website is a team of dedicated writers, researchers, and subject matter experts
                  who are committed to delivering high-quality content that resonates with our audience. We cover a wide
                  range of topics, from the latest advancements in technology to the intricacies of personal growth and
                  development.
                </p>
                <p className="text-gray-600 white:text-gray-300 leading-relaxed mb-4">
                  Our goal is to create a space where our readers can explore new ideas, challenge their assumptions,
                  and grow alongside us. We believe that knowledge and understanding are the keys to personal and
                  professional success, and we're committed to fostering a community of lifelong learners.
                </p>
                <div className="flex justify-end">
                  <Link
                    className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-950 white:bg-gray-50 white:text-gray-900 white:hover:bg-gray-200 white:focus:ring-gray-300"
                    href="#"
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
