/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1laffhDbf4S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function blogpage() {

  const blogs =[
    { id: '1', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '2', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '3', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '4', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '5', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '6', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '7', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '8', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '9', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '10', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    { id: '11', 
      title: 'Taxing Laughter: The Joke Tax Chronicles' ,
      content: "Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem to stop Jokester."
    },
    
  ];

  return (
    <>
      <header className="w-full bg-grey-100 py-12 grey:bg-grey-800">
        <div className="container">
          <div className="mx-auto max-w-3xl space-y-4">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">The Joke Tax Chronicles</h1>
            <div className="flex items-center space-x-4 text-white-500 white:text-white-400">
              <span>By John Doe</span>
              <span>•</span>
              <time dateTime="2023-08-24">August 24, 2023</time>
            </div>
            <p className="text-lg leading-relaxed text-white-600 white:text-white-300">
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
          </div>
        </div>
      </header>

      <div className="flex justify-center gap-10 py-12 px-12 px-12 md:grid-cols-[3fr_1fr]">
        <main>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {blogs.map((blog)=>(
              <article 
              key = {blog.id} 
              className="group overflow-hidden rounded-lg shadow-lg transition-all hover:shadow-xl">
              <Link className="block h-48 w-full overflow-hidden" href="#">
                <img
                  alt="Blog post cover"
                  className="h-full w-full object-cover transition-all group-hover:scale-105"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
              </Link>
              <div className="space-y-2 p-4">
                <h2 className="text-xl font-bold tracking-tight">
                  <Link href="#">{blog.title}</Link>
                </h2>
                <p className="line-clamp-2 text-white-500 white:text-white-400">
                  {blog.content }
                </p>
                <Link
                  className="inline-flex items-center space-x-1 text-sm font-medium text-white-900 hover:text-white-700 white:text-white-50 white:hover:text-white-300"
                  href={`/blogs/${blog.id}`}
                >
                  <span>Read more</span>
                  <ArrowRightIcon className="h-4 w-4" />
                </Link>
              </div>
            </article>
            ))}
          </div>
        </main>
        <aside className="space-y-8">
          <div>
            <h2 className="mb-4 text-xl font-bold">Search</h2>
            <form className="flex items-center space-x-2 bg-white">
              <Input className="flex-1" placeholder="Search blog posts" type="text" />
              <Button type="submit">
                <SearchIcon className="h-5 w-5" />
              </Button>
            </form>
          </div>
          <div>
            <h2 className="mb-4 text-xl font-bold">Categories</h2>
            <nav className="space-y-2">
              <Link
                className="block rounded-md px-4 py-2 text-white-900 hover:bg-white-100 dark:text-white-50 dark:hover:bg-white-800"
                href="#"
              >
                Humor
              </Link>
              <Link
                className="block rounded-md px-4 py-2 text-white-900 hover:bg-white-100 dark:text-white-50 dark:hover:bg-white-800"
                href="#"
              >
                Politics
              </Link>
              <Link
                className="block rounded-md px-4 py-2 text-white-900 hover:bg-white-100 dark:text-white-50 dark:hover:bg-white-800"
                href="#"
              >
                Technology
              </Link>
              <Link
                className="block rounded-md px-4 py-2 text-white-900 hover:bg-white-100 dark:text-white-50 dark:hover:bg-white-800"
                href="#"
              >
                Culture
              </Link>
            </nav>
          </div>
          <div>
            <h2 className="mb-4 text-xl font-bold">Recent Posts</h2>
            <div className="space-y-4">
              <article className="flex items-start space-x-4">
                <Link className="shrink-0" href="#">
                  <img
                    alt="Blog post cover"
                    className="rounded-md object-cover"
                    height={60}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "80/60",
                      objectFit: "cover",
                    }}
                    width={80}
                  />
                </Link>
                <div className="space-y-1">
                  <h3 className="text-lg font-medium">
                    <Link href="#">Taxing Laughter: The Joke Tax Chronicles</Link>
                  </h3>
                  <p className="text-white-500 dark:text-white-400">
                    Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                    throne.
                  </p>
                </div>
              </article>
              <article className="flex items-start space-x-4">
                <Link className="shrink-0" href="#">
                  <img
                    alt="Blog post cover"
                    className="rounded-md object-cover"
                    height={60}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "80/60",
                      objectFit: "cover",
                    }}
                    width={80}
                  />
                </Link>
                <div className="space-y-1">
                  <h3 className="text-lg font-medium">
                    <Link href="#">The Rise of the Joke Tax</Link>
                  </h3>
                  <p className="text-white-500 dark:text-white-400">
                    And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so
                    funny that they couldn't help but laugh.
                  </p>
                </div>
              </article>
              <article className="flex items-start space-x-4">
                <Link className="shrink-0" href="#">
                  <img
                    alt="Blog post cover"
                    className="rounded-md object-cover"
                    height={60}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "80/60",
                      objectFit: "cover",
                    }}
                    width={80}
                  />
                </Link>
                <div className="space-y-1">
                  <h3 className="text-lg font-medium">
                    <Link href="#">The Consequences of the Joke Tax</Link>
                  </h3>
                  <p className="text-white-500 dark:text-white-400">
                    The king was furious, but he couldn't seem to stop Jokester. And then, one day, the people of the
                    kingdom discovered that the jokes left by Jokester were so funny.
                  </p>
                </div>
              </article>
            </div>
          </div>
        </aside>
      </div>
    </>
  )
}

function ArrowRightIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
