/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9qGbER4PFXs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function oneblog() {
  return (
    <div className="bg-white-100 dark:bg-white-800">
      <div className="container mx-auto py-12 md:py-16 lg:py-20">
        <div className="grid grid-cols-1 gap-8 md:gap-12">
          <div className="bg-white dark:bg-white-900 rounded-lg overflow-hidden">
            <img
              alt="Blog Post Cover"
              className="w-full h-[300px] md:h-[400px] object-cover"
              height={600}
              src="/placeholder.svg"
              style={{
                aspectRatio: "1200/600",
                objectFit: "cover",
              }}
              width={1200}
            />
            <div className="p-6 md:p-8">
              <h1 className="text-3xl md:text-4xl font-bold mb-2">Lorem ipsum</h1>
              <div className="flex items-center text-white-500 dark:text-white-400 mb-4">
                <span className="mr-2">By Jane Doe</span>
                <span className="mx-2">•</span>
                <span>May 25, 2024</span>
              </div>
              <p className="text-white-600 dark:text-white-300 leading-relaxed mb-4">
                In the ever-evolving landscape of web development, the integration of AI has become a game-changer. As
                we delve into the future, we explore the profound impact of this transformative technology on the way we
                build and interact with the web.
              </p>
              <p className="text-white-600 dark:text-white-300 leading-relaxed mb-4">
                AI-powered tools and frameworks are revolutionizing the web development process, from automated code
                generation to intelligent user interface design. By harnessing the power of machine learning and natural
                language processing, developers can now create more efficient, scalable, and user-friendly web
                applications with unprecedented speed and accuracy.
              </p>
              <p className="text-white-600 dark:text-white-300 leading-relaxed mb-4">
                In this blog post, we'll dive deep into the world of AI-driven web development, exploring the latest
                technologies, best practices, and real-world case studies that showcase the transformative potential of
                this cutting-edge field. Whether you're a seasoned developer or just starting your journey, this article
                will equip you with the knowledge and insights to leverage AI and shape the future of the web.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
