/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ghn2IhQMUYx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function signinComp() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Join our growing community
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  Sign up today and get access to exclusive content, resources, and a vibrant community of fellow
                  bloggers.
                </p>
              </div>
              <div className="flex flex-col gap-4">
                <Button className="w-full">Sign Up</Button>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Already have an account?
                  <Link className="font-medium underline underline-offset-2" href="#">
                    Log in
                  </Link>
                </p>
              </div>
            </div>
            <Card className="w-full">
              <CardHeader className="space-y-1">
                <CardTitle className="text-2xl">Create an account</CardTitle>
                <CardDescription>Enter your details below to join our community.</CardDescription>
              </CardHeader>
              <CardContent className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="John Doe" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="john@example.com" type="email" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="password">Password</Label>
                  <Input id="password" type="password" />
                </div>
              </CardContent>
              <CardFooter>
                <Button className="w-full" type="submit">
                  Sign Up
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Exclusive content and community
                </h2>
                <p className="text-gray-500 md:text-xl dark:text-gray-400">
                  As a member, you'll get access to our exclusive blog posts, webinars, and a vibrant community of
                  fellow bloggers.
                </p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                  <FileTextIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <h3 className="mt-2 text-lg font-semibold">Exclusive Content</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Access our latest blog posts, guides, and resources.
                  </p>
                </div>
                <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                  <UsersIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <h3 className="mt-2 text-lg font-semibold">Community</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Connect with other bloggers and share ideas.
                  </p>
                </div>
                <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                  <BookmarkIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <h3 className="mt-2 text-lg font-semibold">Saved Content</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Save your favorite posts and access them anytime.
                  </p>
                </div>
                <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                  <AwardIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <h3 className="mt-2 text-lg font-semibold">Badges and Rewards</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Earn badges and rewards for your contributions.
                  </p>
                </div>
              </div>
            </div>
            <img
              alt="Community"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
    </>
  )
}

function AwardIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}


function BookmarkIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function FileTextIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </svg>
  )
}


function UsersIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
